C++: # Language
  beautifiers: # Enable beautifier
    - ClangFormat
  ClangFormat: # Beautifier options
    prefer_beautifier_config: true
    ClangFormat: # Executable options
      path: "./.clang-format"
