TEMPLATE = lib

QT += core qml quick quickcontrols2 sql svg printsupport

CONFIG += c++17

RESOURCES += config/config.qrc \
    json/json.qrc \
    schema/schema.qrc

INCLUDEPATH += .

SOURCES += \
    database/queryexecutor.cpp \
    network/networkexception.cpp \
    network/networkthread.cpp \
    network/requestlogger.cpp \
    network/serverrequest.cpp \
    network/serverresponse.cpp \
    qmlapi/qmlexpensetransactionmodel.cpp \
    qmlapi/qmlstockitemcountrecord.cpp \
    qmlapi/qmlstockitemmodel.cpp \
    qmlapi/qmluserprofile.cpp \
    queryexecutors/client/clientexecutor.cpp \
    queryexecutors/client/viewclients.cpp \
    queryexecutors/dashboard/dashboardexecutor.cpp \
    queryexecutors/dashboard/viewdashboard.cpp \
    queryexecutors/debtor/adddebtor.cpp \
    queryexecutors/debtor/debtorexecutor.cpp \
    queryexecutors/debtor/removedebtor.cpp \
    queryexecutors/debtor/updatedebtor.cpp \
    queryexecutors/debtor/viewdebtordetails.cpp \
    queryexecutors/debtor/viewdebtors.cpp \
    queryexecutors/debtor/viewdebttransactions.cpp \
    queryexecutors/expense/addexpensetransaction.cpp \
    queryexecutors/expense/expenseexecutor.cpp \
    queryexecutors/expense/viewexpensereport.cpp \
    queryexecutors/expense/viewexpensetransactions.cpp \
    queryexecutors/income/addincometransaction.cpp \
    queryexecutors/income/incomeexecutor.cpp \
    queryexecutors/income/viewincomereport.cpp \
    queryexecutors/income/viewincometransactions.cpp \
    queryexecutors/purchase/addpurchasetransaction.cpp \
    queryexecutors/purchase/purchaseexecutor.cpp \
    queryexecutors/purchase/removepurchasetransaction.cpp \
    queryexecutors/purchase/removepurchasetransactionitem.cpp \
    queryexecutors/purchase/updatesuspendedpurchasetransaction.cpp \
    queryexecutors/purchase/viewpurchasecart.cpp \
    queryexecutors/purchase/viewpurchasehome.cpp \
    queryexecutors/purchase/viewpurchasereport.cpp \
    queryexecutors/purchase/viewpurchasetransactions.cpp \
    queryexecutors/sales/addsaletransaction.cpp \
    queryexecutors/sales/removesaletransaction.cpp \
    queryexecutors/sales/removesaletransactionitem.cpp \
    queryexecutors/sales/saleexecutor.cpp \
    queryexecutors/sales/updatesuspendedsaletransaction.cpp \
    queryexecutors/sales/viewsalecart.cpp \
    queryexecutors/sales/viewsalehome.cpp \
    queryexecutors/sales/viewsalereport.cpp \
    queryexecutors/sales/viewsaletransactionitems.cpp \
    queryexecutors/sales/viewsaletransactions.cpp \
    queryexecutors/stock/addstockitem.cpp \
    queryexecutors/stock/filterstockcategories.cpp \
    queryexecutors/stock/filterstockcategoriesbyitem.cpp \
    queryexecutors/stock/filterstockitemcount.cpp \
    queryexecutors/stock/filterstockitems.cpp \
    queryexecutors/stock/removestockitem.cpp \
    queryexecutors/stock/stockexecutor.cpp \
    queryexecutors/stock/updatestockitem.cpp \
    queryexecutors/purchase/viewpurchasetransactionitems.cpp \
    queryexecutors/stock/viewstockcategories.cpp \
    queryexecutors/stock/viewstockitemcount.cpp \
    queryexecutors/stock/viewstockitemdetails.cpp \
    queryexecutors/stock/viewstockitems.cpp \
    queryexecutors/stock/viewstockreport.cpp \
    queryexecutors/user/activateuser.cpp \
    queryexecutors/user/adduser.cpp \
    queryexecutors/user/changepassword.cpp \
    queryexecutors/user/removeuser.cpp \
    queryexecutors/user/signinuser.cpp \
    queryexecutors/user/signoutuser.cpp \
    queryexecutors/user/signupuser.cpp \
    queryexecutors/user/updateuserprivileges.cpp \
    queryexecutors/user/userexecutor.cpp \
    queryexecutors/user/viewuserdetails.cpp \
    queryexecutors/user/viewuserprivileges.cpp \
    queryexecutors/user/viewusers.cpp \
    sqlmanager/usersqlmanager.cpp \
    sqlmanager/abstractsqlmanager.cpp \
    database/databasethread.cpp \
    database/databaseserver.cpp \
    database/databasecreator.cpp \
    database/databaseexception.cpp \
    database/queryrequest.cpp \
    database/queryresult.cpp \
    qmlapi/qmldashboardhomemodel.cpp \
    sqlmanager/dashboardsqlmanager.cpp \
    qmlapi/qmlstockitempusher.cpp \
    sqlmanager/stocksqlmanager.cpp \
    user/businessadmin.cpp \
    user/businessstore.cpp \
    user/businessstoremodel.cpp \
    user/userprofile.cpp \
    database/databaseutils.cpp \
    models/abstractvisuallistmodel.cpp \
    pusher/abstractpusher.cpp \
    qmlapi/qmlsalecartmodel.cpp \
    sqlmanager/salesqlmanager.cpp \
    qmlapi/qmlsaletransactionmodel.cpp \
    qmlapi/qmldoublevalidator.cpp \
    qmlapi/qmlsaletransactionitemmodel.cpp \
    qmlapi/qmlstockcategorymodel.cpp \
    qmlapi/qmldebtormodel.cpp \
    sqlmanager/debtorsqlmanager.cpp \
    qmlapi/qmlsalehomemodel.cpp \
    models/saletotalrevenuemodel.cpp \
    models/salemostsolditemmodel.cpp \
    detailrecord/abstractdetailrecord.cpp \
    qmlapi/qmlstockitemdetailrecord.cpp \
    models/abstracttransactionmodel.cpp \
    models/abstracttransactionitemmodel.cpp \
    user/businessdetails.cpp \
    widgets/dialogs.cpp \
    qmlapi/qmlclientmodel.cpp \
    sqlmanager/clientsqlmanager.cpp \
    qmlapi/qmldebttransactionmodel.cpp \
    models/debtpaymentmodel.cpp \
    qmlapi/qmldebtordetailrecord.cpp \
    models/salepaymentmodel.cpp \
    qmlapi/qmldatabasecreator.cpp \
    config/config.cpp \
    json/messagecenter.cpp \
    models/abstracthomemodel.cpp \
    qmlapi/qmlnotifier.cpp \
    qmlapi/qmlpurchasehomemodel.cpp \
    sqlmanager/purchasesqlmanager.cpp \
    qmlapi/qmlpurchasecartmodel.cpp \
    models/purchasepaymentmodel.cpp \
    qmlapi/qmlincomehomemodel.cpp \
    qmlapi/qmlincomepusher.cpp \
    qmlapi/qmlexpensepusher.cpp \
    qmlapi/qmlexpensehomemodel.cpp \
    qmlapi/qmlcreditormodel.cpp \
    sqlmanager/incomesqlmanager.cpp \
    sqlmanager/expensesqlmanager.cpp \
    models/abstractvisualtablemodel.cpp \
    qmlapi/qmlincometransactionmodel.cpp \
    qmlapi/qmlusermodel.cpp \
    qmlapi/qmluserprivilegemodel.cpp \
    json/userprivilegecenter.cpp \
    models/userprivilegemodel.cpp \
    qmlapi/qmluserdetailrecord.cpp \
    qmlapi/qmlsettings.cpp \
    singletons/settings.cpp \
    qmlapi/qmlpurchasetransactionmodel.cpp \
    qmlapi/qmlpurchasetransactionitemmodel.cpp \
    qmlapi/qmlreceiptprinter.cpp \
    models/receiptcartmodel.cpp \
    singletons/logger.cpp \
    qmlapi/qmlstockreportmodel.cpp \
    qmlapi/qmlsalereportmodel.cpp \
    qmlapi/qmlpurchasereportmodel.cpp \
    qmlapi/qmlexpensereportmodel.cpp \
    qmlapi/qmlincomereportmodel.cpp

HEADERS += \
    database/databaseerror.h \
    database/queryexecutor.h \
    network/networkerror.h \
    network/networkexception.h \
    network/networkthread.h \
    network/networkurl.h \
    network/requestlogger.h \
    network/serverrequest.h \
    network/serverresponse.h \
    qmlapi/qmlexpensetransactionmodel.h \
    qmlapi/qmlstockitemcountrecord.h \
    qmlapi/qmlstockitemmodel.h \
    qmlapi/qmluserprofile.h \
    queryexecutors/client.h \
    queryexecutors/client/clientexecutor.h \
    queryexecutors/client/viewclients.h \
    queryexecutors/dashboard.h \
    queryexecutors/dashboard/dashboardexecutor.h \
    queryexecutors/dashboard/viewdashboard.h \
    queryexecutors/debtor.h \
    queryexecutors/debtor/adddebtor.h \
    queryexecutors/debtor/debtorexecutor.h \
    queryexecutors/debtor/removedebtor.h \
    queryexecutors/debtor/updatedebtor.h \
    queryexecutors/debtor/viewdebtordetails.h \
    queryexecutors/debtor/viewdebtors.h \
    queryexecutors/debtor/viewdebttransactions.h \
    queryexecutors/expense.h \
    queryexecutors/expense/addexpensetransaction.h \
    queryexecutors/expense/expenseexecutor.h \
    queryexecutors/expense/viewexpensereport.h \
    queryexecutors/expense/viewexpensetransactions.h \
    queryexecutors/income.h \
    queryexecutors/income/addincometransaction.h \
    queryexecutors/income/incomeexecutor.h \
    queryexecutors/income/viewincomereport.h \
    queryexecutors/income/viewincometransactions.h \
    queryexecutors/purchase.h \
    queryexecutors/purchase/addpurchasetransaction.h \
    queryexecutors/purchase/purchaseexecutor.h \
    queryexecutors/purchase/removepurchasetransaction.h \
    queryexecutors/purchase/removepurchasetransactionitem.h \
    queryexecutors/purchase/updatesuspendedpurchasetransaction.h \
    queryexecutors/purchase/viewpurchasecart.h \
    queryexecutors/purchase/viewpurchasehome.h \
    queryexecutors/purchase/viewpurchasereport.h \
    queryexecutors/purchase/viewpurchasetransactions.h \
    queryexecutors/sales.h \
    queryexecutors/sales/addsaletransaction.h \
    queryexecutors/sales/removesaletransaction.h \
    queryexecutors/sales/removesaletransactionitem.h \
    queryexecutors/sales/saleexecutor.h \
    queryexecutors/sales/updatesuspendedsaletransaction.h \
    queryexecutors/sales/viewsalecart.h \
    queryexecutors/sales/viewsalehome.h \
    queryexecutors/sales/viewsalereport.h \
    queryexecutors/sales/viewsaletransactionitems.h \
    queryexecutors/sales/viewsaletransactions.h \
    queryexecutors/stock.h \
    queryexecutors/stock/addstockitem.h \
    queryexecutors/stock/filterstockcategories.h \
    queryexecutors/stock/filterstockcategoriesbyitem.h \
    queryexecutors/stock/filterstockitemcount.h \
    queryexecutors/stock/filterstockitems.h \
    queryexecutors/stock/removestockitem.h \
    queryexecutors/stock/stockexecutor.h \
    queryexecutors/stock/updatestockitem.h \
    queryexecutors/purchase/viewpurchasetransactionitems.h \
    queryexecutors/stock/viewstockcategories.h \
    queryexecutors/stock/viewstockitemcount.h \
    queryexecutors/stock/viewstockitemdetails.h \
    queryexecutors/stock/viewstockitems.h \
    queryexecutors/stock/viewstockreport.h \
    queryexecutors/user.h \
    queryexecutors/user/activateuser.h \
    queryexecutors/user/adduser.h \
    queryexecutors/user/changepassword.h \
    queryexecutors/user/removeuser.h \
    queryexecutors/user/signinuser.h \
    queryexecutors/user/signoutuser.h \
    queryexecutors/user/signupuser.h \
    queryexecutors/user/updateuserprivileges.h \
    queryexecutors/user/userexecutor.h \
    queryexecutors/user/viewuserdetails.h \
    queryexecutors/user/viewuserprivileges.h \
    queryexecutors/user/viewusers.h \
    schema/schema.h \
    sqlmanager/usersqlmanager.h \
    sqlmanager/abstractsqlmanager.h \
    database/databasethread.h \
    database/databaseserver.h \
    database/databasecreator.h \
    database/databaseexception.h \
    database/queryrequest.h \
    database/queryresult.h \
    qmlapi/qmldashboardhomemodel.h \
    sqlmanager/dashboardsqlmanager.h \
    qmlapi/qmlstockitempusher.h \
    sqlmanager/stocksqlmanager.h \
    user/businessadmin.h \
    user/businessstore.h \
    user/businessstoremodel.h \
    user/userprofile.h \
    database/databaseutils.h \
    models/abstractvisuallistmodel.h \
    pusher/abstractpusher.h \
    qmlapi/qmlsalecartmodel.h \
    sqlmanager/salesqlmanager.h \
    qmlapi/qmlsaletransactionmodel.h \
    qmlapi/qmldoublevalidator.h \
    qmlapi/qmlsaletransactionitemmodel.h \
    qmlapi/qmlstockcategorymodel.h \
    qmlapi/qmldebtormodel.h \
    sqlmanager/debtorsqlmanager.h \
    qmlapi/qmlsalehomemodel.h \
    models/saletotalrevenuemodel.h \
    models/salemostsolditemmodel.h \
    detailrecord/abstractdetailrecord.h \
    qmlapi/qmlstockitemdetailrecord.h \
    models/abstracttransactionmodel.h \
    models/abstracttransactionitemmodel.h \
    user/businessdetails.h \
    utility/purchaseutils.h \
    utility/stockutils.h \
    widgets/dialogs.h \
    qmlapi/qmlclientmodel.h \
    sqlmanager/clientsqlmanager.h \
    qmlapi/qmldebttransactionmodel.h \
    models/debtpaymentmodel.h \
    qmlapi/qmldebtordetailrecord.h \
    utility/debtorutils.h \
    utility/saleutils.h \
    models/salepaymentmodel.h \
    qmlapi/qmldatabasecreator.h \
    config/config.h \
    json/messagecenter.h \
    models/abstracthomemodel.h \
    qmlapi/qmlnotifier.h \
    qmlapi/qmlpurchasehomemodel.h \
    sqlmanager/purchasesqlmanager.h \
    qmlapi/qmlpurchasecartmodel.h \
    models/purchasepaymentmodel.h \
    qmlapi/qmlincomehomemodel.h \
    qmlapi/qmlincomepusher.h \
    qmlapi/qmlexpensepusher.h \
    qmlapi/qmlexpensehomemodel.h \
    qmlapi/qmlcreditormodel.h \
    sqlmanager/incomesqlmanager.h \
    sqlmanager/expensesqlmanager.h \
    models/abstractvisualtablemodel.h \
    qmlapi/qmlincometransactionmodel.h \
    qmlapi/qmlusermodel.h \
    qmlapi/qmluserprivilegemodel.h \
    json/userprivilegecenter.h \
    models/userprivilegemodel.h \
    qmlapi/qmluserdetailrecord.h \
    qmlapi/qmlsettings.h \
    singletons/settings.h \
    qmlapi/qmlpurchasetransactionmodel.h \
    qmlapi/qmlpurchasetransactionitemmodel.h \
    qmlapi/qmlreceiptprinter.h \
    models/receiptcartmodel.h \
    singletons/logger.h \
    qmlapi/qmlstockreportmodel.h \
    qmlapi/qmlsalereportmodel.h \
    qmlapi/qmlpurchasereportmodel.h \
    qmlapi/qmlexpensereportmodel.h \
    qmlapi/qmlincomereportmodel.h

DISTFILES +=
