name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2

    - name: Install Qt
      env:
        #5.13.1
        QT_VERSION_FULL: 5.13.1
      run: |
        export QT_VERSION_MAJOR_MINOR=$(echo $QT_VERSION_FULL | sed 's/\.[^.]*$//')
        export QT_VERSION_SCRIPT=$(echo $QT_VERSION_FULL | sed -e 's/\.//g')
        sudo apt-get install unzip wget build-essential mesa-common-dev -y
        wget https://download.qt.io/archive/qt/${QT_VERSION_MAJOR_MINOR}/${QT_VERSION_FULL}/qt-opensource-linux-x64-${QT_VERSION_FULL}.run
        chmod +x qt-opensource-linux-x64-${QT_VERSION_FULL}.run
        ./qt-opensource-linux-x64-${QT_VERSION_FULL}.run --script scripts/qt-noninteractive.qs -platform minimal --verbose email=${{ secrets.QT_INSTALLER_EMAIL }} password=${{ secrets.QT_INSTALLER_PASSWORD }}

    - name: Build app and run tests
      env:
        #5.13.1
        QT_VERSION_FULL: 5.13.1
      run: |
        export QTDIR=$HOME/Qt/$QT_VERSION_FULL/gcc_64
        qmake -project
        qmake CONFIG+=release
        make -j`nproc`
        make check
        
