# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      
    - name: Install Qt
      env:
        QT_VERSION_A: 5.13
        QT_VERSION_B: 5.13.1
        QT_VERSION_SCRIPT: 5131
      run: |
        apt-get update
        apt-get install unzip wget
        wget https://download.qt.io/archive/qt/${QT_VERSION_A}/${QT_VERSION_B}/qt-opensource-linux-x64-${QT_VERSION_B}.run
        chmod +x qt-opensource-linux-x64-${QT_VERSION_B}.run
        ./qt-opensource-linux-x64-${QT_VERSION_B}.run --script deployment/qt-noninteractive.qs -platform minimal

    - name: Build app and run tests
      run: |
        qmake -project
        qmake CONFIG+=release
        make
        make check
        
