name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  # Semver (e.g. 5.13.1)
  QT_VERSION: 5.13.1

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: Install Qt
      env:
        QT_INSTALL_DIR: $HOME/Qt
      run: |
        sudo apt-get update
        sudo apt-get install unzip wget build-essential mesa-common-dev libglu1-mesa-dev -y
        python -m pip install --upgrade pip
        sudo pip install aqtinstall
        mkdir $QTDIR
        sudo aqt install --outputdir $QT_INSTALL_DIR $QT_VERSION linux desktop

    - name: Build app and run tests
      env:
        QTDIR: QTDIR=$HOME/Qt/$QT_VERSION/gcc_64
      run: |
        $QTDIR/bin/qmake CONFIG+=release
        make -j`nproc`
        export RRCORE=$PWD/src/rrcore
        export LD_LIBRARY_PATH=$QTDIR/lib
        export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$RRCORE
        export QT_QPA_PLATFORM=offscreen
        make check
        
